version: '3.5'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 8080:80
      - 443:443
    volumes:
      - type: bind
        source: ./
        target: /app
        read_only: false
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx:/etc/nginx/certs
    working_dir: /app
  php-fpm:
    build: ./ops/php-fpm
    volumes:
      - type: bind
        source: ./
        target: /app
        read_only: false
    working_dir: /app
